image: node:10.12.0

stages:
 - build
 - test
 - deploy

heroku-deployment:
 stage: deploy
 script:
  - npm install --production
  - (echo "machine git.heroku.com"; echo " login aparnaunny@gmail.com"; echo " password $HEROKU_PASSWORD") > ~/.netrc
  - git push https://git.heroku.com/test-app05.git HEAD:master